# Generated by Django 3.1.5 on 2021-01-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='匿名ユーザー', max_length=30, verbose_name='ユーザー名'),
        ),
    ]
