# Generated by Django 3.1.5 on 2021-01-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='匿名ユーザー', max_length=50, null=True, verbose_name='ユーザー名'),
        ),
    ]
