# Generated by Django 3.1.5 on 2021-01-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210109_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='匿名ユーザー', max_length=50, null=True, verbose_name='ユーザー名'),
        ),
    ]
