# Generated by Django 3.1.5 on 2021-01-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='name',
            field=models.CharField(blank=True, default='Acount', max_length=200, null=True),
        ),
    ]
