# Generated by Django 3.1.5 on 2021-01-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movieblog_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='selectMovie',
        ),
    ]
