# Generated by Django 3.1.5 on 2021-01-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_auto_20210110_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moviename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='movienames',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movieapp.moviename'),
        ),
    ]
