# Generated by Django 3.1.5 on 2021-01-23 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0002_auto_20210123_1512'),
        ('movieapp', '0002_movieblog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieblog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movieblog',
            name='movietitle',
        ),
        migrations.RemoveField(
            model_name='movieblog',
            name='tags',
        ),
        migrations.AddField(
            model_name='movieblog',
            name='movieinfo',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviedb.movieinfo'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Movietitle',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
