# Generated by Django 3.1.5 on 2021-01-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_auto_20210110_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='movienames',
        ),
        migrations.AddField(
            model_name='post',
            name='movietitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Moviename',
        ),
    ]
