# Generated by Django 3.1.5 on 2021-01-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_auto_20210113_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
