# Generated by Django 3.1.5 on 2021-01-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='title',
            new_name='movietitle',
        ),
    ]
