# Generated by Django 3.1.5 on 2021-01-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0002_auto_20210120_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='release',
            field=models.DateField(),
        ),
    ]
