# Generated by Django 3.1.5 on 2021-01-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0003_auto_20210120_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='created',
        ),
    ]
