# Generated by Django 3.1.5 on 2021-01-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0004_remove_movieinfo_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='release',
        ),
    ]
